### ISSUE TITLE
Problems with 0.88.1 and 0.88.2

### ISSUE THREAD

**Issue by carlostico** [custom-components/usps_mail#13]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.usps_mail.camera'; 'custom_components.usps_mail' is not a package

**Comment by ludeeus** [comment]
This should not happen.. did you move any files locally?

**Comment by carlostico** [comment]
Nothing , just updated to the latest version of HA first 0.88.1 and then 0.88.2  and got that message 
After that I created a folder on custom_components called usps_mail and inside i put the usps_mail.py changing the name ti   __init__.py and seems that doing that fixed the problem
